services:
  db:
    container_name: YuGiOhBot_postgres
    image: postgres:16.1-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=testing
      - PGDATA=pgdata
      - YUGIOH_ENV=Docker
      - LANG=en_US.utf-8
#    command: "-c fsync=off -c synchronous_commit=off -c full_page_writes=off"
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./yugioh.sql:/docker-entrypoint-initdb.d/yugioh.sql
      - ./guilds.sql:/docker-entrypoint-initdb.d/guilds.sql
  dotnet:
    container_name: YuGiOhBot_dotnet
    #    image: mcr.microsoft.com/dotnet/sdk:6.0.302
    #    depends_on:
    #      - db
    #    volumes:
    #      - .:/src
    #    working_dir: /src
    ##        command: sh -c "dotnet test"
    ##    entrypoint: "dotnet test --verbosity normal --no-build" #build disabled until Rider recognizes artifacts/changes built in Docker
    #    entrypoint: "dotnet test --verbosity normal"
    depends_on:
      - db
    build:
      context: .
      dockerfile: dotnet.Dockerfile
#volumes:
#  postgres-data:
networks:
  default:
    driver: bridge

#todo think about changing alpine to debian/ubuntu due to the server the bot runs on is ubuntu and not alpine